### ISSUE TITLE
Python script error when activating WeTek CEC addon

### ISSUE THREAD

**Issue by andre099** [lrusak/wetek-cec#1]
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmcaddon.Addon' object has no attribute 'setSettings'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.system.wetek-cec/default.py", line 85, in <module>
                                                startup()
                                              File "/storage/.kodi/addons/service.system.wetek-cec/default.py", line 81, in startup
                                                __addon__.setSettings('enable_cec', 'true')
                                            AttributeError: 'xbmcaddon.Addon' object has no attribute 'setSettings'
                                            -->End of Python script error report<--

**Comment by Shani-08** [comment]
i got the same issue as well because setSettings is not the correct name, it should be setSetting i believe. However, after that, whenever i rebooted it sets the cec_mode to blank. I dont think we need startup() function as it just reads the current state and override the user settings. commenting it out makes it work and i can see cec working.

**Comment by lrusak** [comment]
Thanks for reporting, this is fixed in @b28bd8569c7b9ba6bec7d8ad9bd23bf57bfe462f

Please update to version (6.0.1)[https://dl.dropboxusercontent.com/u/21742150/service.system.wetek-cec-6.0.1.zip]
